package demonmodders.crymod.common.core;

import java.util.Arrays;

import com.google.common.eventbus.EventBus;

import cpw.mods.fml.common.DummyModContainer;
import cpw.mods.fml.common.LoadController;
import cpw.mods.fml.common.ModMetadata;

public class CrymodCoreMC extends DummyModContainer {
	
	public CrymodCoreMC() {
		super(new ModMetadata());
		
		ModMetadata meta = getMetadata();
		meta.autogenerated = false;
		meta.authorList = Arrays.asList("resinresin", "diesieben07");
		meta.name = "Summoningmod Core";
		meta.modId = "SummoningModCore";
		meta.description = "Provides Core functionality for the Summoningmod";
	}

	@Override
	public boolean registerBus(EventBus bus, LoadController controller) {
		return true;
	}
}