package demonmodders.crymod.common.core;

import java.util.Arrays;
import java.util.Map;

import net.minecraft.nbt.NBTBase;
import net.minecraft.nbt.NBTTagCompound;
import net.minecraft.world.storage.SaveHandler;
import net.minecraft.world.storage.WorldInfo;

import com.google.common.eventbus.EventBus;

import cpw.mods.fml.common.DummyModContainer;
import cpw.mods.fml.common.LoadController;
import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.common.WorldAccessContainer;

public class CrymodModContainer extends DummyModContainer {
	
	public CrymodModContainer() {
		super(new ModMetadata());
		
		ModMetadata meta = getMetadata();
		meta.autogenerated = false;
		meta.authorList = Arrays.asList("resinresin", "diesieben07");
		meta.name = "Summoningmod Core";
		meta.modId = "SummoningModCore";
		meta.description = "Provides Core functionality for the Summoningmod";
	}

	@Override
	public boolean registerBus(EventBus bus, LoadController controller) {
		return true;
	}
}